services:
  m4brew_template_test:
    image: matxby/m4brew:1.4.0
    container_name: m4brew-template-test

    ports:
      - "8586:8080"

    environment:
      - TZ=Europe/London
      - PUID=1026
      - PGID=100
      - DOCKER_NETWORK=matt-net

    volumes:
      - /mnt/cache/appdata/m4brew/config-template-test:/config:rw
      - /mnt/remotes/192.168.4.4_media/Audiobooks:/audiobooks:rw,slave
      - /var/run/docker.sock:/var/run/docker.sock:rw

    networks:
      - matt-net

    restart: unless-stopped

networks:
  matt-net:
    external: true
